PARAMS: dict = {   'MomentumV8Strategy': {   'ABNB': {   '10m': {   'body_ratio_threshold': 0.5,
                                                     'price_move_pct': 1.5,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.5}},
                              'ALAB': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.0,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 2.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.0}},
                              'ASTS': {   '10m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 3.5,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.5}},
                              'CSCO': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.5,
                                                     'take_profit_pct': 1.0,
                                                     'trail_stop_pct': 1.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.5}},
                              'DIS': {   '10m': {   'body_ratio_threshold': 0.5,
                                                    'price_move_pct': 3.5,
                                                    'take_profit_pct': 1.0,
                                                    'trail_stop_pct': 1.0,
                                                    'vol_len': 5,
                                                    'vol_multiplier': 3.5}},
                              'ELVN': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.5,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 1.5,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 2.5}},
                              'FRSH': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.5,
                                                     'take_profit_pct': 1.0,
                                                     'trail_stop_pct': 1.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.0}},
                              'HALO': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 0.5,
                                                     'take_profit_pct': 1.5,
                                                     'trail_stop_pct': 1.0,
                                                     'vol_len': 7,
                                                     'vol_multiplier': 1.2}},
                              'HPQ': {   '10m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 2.5,
                                                    'take_profit_pct': 1.0,
                                                    'trail_stop_pct': 3.5,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 3.0}},
                              'ISRG': {   '10m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 0.8,
                                                     'take_profit_pct': 1.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 2.0}},
                              'JD': {   '10m': {   'body_ratio_threshold': 0.7,
                                                   'price_move_pct': 0.5,
                                                   'take_profit_pct': 1.5,
                                                   'trail_stop_pct': 2.5,
                                                   'vol_len': 10,
                                                   'vol_multiplier': 3.5}},
                              'LUV': {   '10m': {   'body_ratio_threshold': 0.3,
                                                    'price_move_pct': 3.5,
                                                    'take_profit_pct': 2.0,
                                                    'trail_stop_pct': 2.5,
                                                    'vol_len': 7,
                                                    'vol_multiplier': 3.0}},
                              'NXT': {   '10m': {   'body_ratio_threshold': 0.3,
                                                    'price_move_pct': 3.5,
                                                    'take_profit_pct': 2.0,
                                                    'trail_stop_pct': 1.0,
                                                    'vol_len': 5,
                                                    'vol_multiplier': 3.5}},
                              'PATH': {   '10m': {   'body_ratio_threshold': 0.5,
                                                     'price_move_pct': 1.8,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 3.5,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 1.2}},
                              'PYPL': {   '10m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 3.0,
                                                     'take_profit_pct': 1.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 1.8}},
                              'TMO': {   '10m': {   'body_ratio_threshold': 0.5,
                                                    'price_move_pct': 3.0,
                                                    'take_profit_pct': 1.0,
                                                    'trail_stop_pct': 2.5,
                                                    'vol_len': 5,
                                                    'vol_multiplier': 1.8}},
                              'UAA': {   '10m': {   'body_ratio_threshold': 0.3,
                                                    'price_move_pct': 3.5,
                                                    'take_profit_pct': 2.0,
                                                    'trail_stop_pct': 3.0,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 1.2}},
                              'VOYG': {   '10m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 3.0,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 1.0,
                                                     'vol_len': 7,
                                                     'vol_multiplier': 3.5}},
                              'XP': {   '10m': {   'body_ratio_threshold': 0.3,
                                                   'price_move_pct': 3.0,
                                                   'take_profit_pct': 2.0,
                                                   'trail_stop_pct': 2.5,
                                                   'vol_len': 7,
                                                   'vol_multiplier': 2.0}}}}
# === Ticker ranking by sortino (best combo per ticker) ===
#     #  ticker      sortino  vol_len   vol_mult   price_pct   trail_pct   tp_pct   body_ratio
#     1  LUV           +9.15        7       3.00        3.50        2.50     2.00         0.30
#     2  JD            +3.27       10       3.50        0.50        2.50     1.50         0.70
#     3  ABNB          +2.92        5       3.50        1.50        3.00     2.00         0.50
#     4  CSCO          +1.68        5       3.50        3.50        1.00     1.00         0.70
#     5  XP            +1.30        7       2.00        3.00        2.50     2.00         0.30
#     6  HPQ           +1.20       10       3.00        2.50        3.50     1.00         0.70
#     7  TMO           +1.16        5       1.80        3.00        2.50     1.00         0.50
#     8  DIS           +1.09        5       3.50        3.50        1.00     1.00         0.50
#     9  FRSH          +1.01        5       3.00        3.50        1.00     1.00         0.70
#    10  PYPL          +1.00        5       1.80        3.00        3.00     1.50         0.30
#    11  UAA           +0.96       10       1.20        3.50        3.00     2.00         0.30
#    12  PATH          +0.71        5       1.20        1.80        3.50     2.00         0.50
#    13  HALO          +0.66        7       1.20        0.50        1.00     1.50         0.70
#    14  ELVN          +0.43       10       2.50        3.50        1.50     2.00         0.70