PARAMS: dict = {   'MomentumV8Strategy': {   'ABNB': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.0,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 3.5,
                                                     'vol_len': 7,
                                                     'vol_multiplier': 3.5}},
                              'ALAB': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.0,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 2.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.0}},
                              'ASTS': {   '10m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 3.5,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.5}},
                              'CSCO': {   '10m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 1.8,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 1.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 2.0}},
                              'DIS': {   '10m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 2.5,
                                                    'take_profit_pct': 2.0,
                                                    'trail_stop_pct': 3.0,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 1.5}},
                              'ELVN': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.5,
                                                     'take_profit_pct': 1.0,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.5}},
                              'FRSH': {   '10m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 2.5,
                                                     'take_profit_pct': 1.5,
                                                     'trail_stop_pct': 1.0,
                                                     'vol_len': 7,
                                                     'vol_multiplier': 2.5}},
                              'HALO': {   '10m': {   'body_ratio_threshold': 0.5,
                                                     'price_move_pct': 2.5,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 0.5}},
                              'HPQ': {   '10m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 3.0,
                                                    'take_profit_pct': 1.0,
                                                    'trail_stop_pct': 1.5,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 3.0}},
                              'ISRG': {   '10m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 0.8,
                                                     'take_profit_pct': 1.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 2.0}},
                              'JD': {   '10m': {   'body_ratio_threshold': 0.7,
                                                   'price_move_pct': 1.0,
                                                   'take_profit_pct': 2.0,
                                                   'trail_stop_pct': 2.5,
                                                   'vol_len': 5,
                                                   'vol_multiplier': 1.2}},
                              'LUV': {   '10m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 3.5,
                                                    'take_profit_pct': 2.0,
                                                    'trail_stop_pct': 3.0,
                                                    'vol_len': 7,
                                                    'vol_multiplier': 3.0}},
                              'NXT': {   '10m': {   'body_ratio_threshold': 0.3,
                                                    'price_move_pct': 3.5,
                                                    'take_profit_pct': 2.0,
                                                    'trail_stop_pct': 1.0,
                                                    'vol_len': 5,
                                                    'vol_multiplier': 3.5}},
                              'PATH': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.5,
                                                     'take_profit_pct': 1.0,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 3.5}},
                              'PYPL': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.5,
                                                     'take_profit_pct': 1.5,
                                                     'trail_stop_pct': 3.5,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 1.0}},
                              'TMO': {   '10m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 2.5,
                                                    'take_profit_pct': 2.0,
                                                    'trail_stop_pct': 1.0,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 1.5}},
                              'UAA': {   '10m': {   'body_ratio_threshold': 0.3,
                                                    'price_move_pct': 1.2,
                                                    'take_profit_pct': 2.0,
                                                    'trail_stop_pct': 1.0,
                                                    'vol_len': 7,
                                                    'vol_multiplier': 3.5}},
                              'VOYG': {   '10m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 3.0,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 1.0,
                                                     'vol_len': 7,
                                                     'vol_multiplier': 3.5}},
                              'XP': {   '10m': {   'body_ratio_threshold': 0.3,
                                                   'price_move_pct': 3.0,
                                                   'take_profit_pct': 2.0,
                                                   'trail_stop_pct': 3.0,
                                                   'vol_len': 7,
                                                   'vol_multiplier': 0.7}}}}
