PARAMS: dict = {   'MomentumV8Strategy': {   'A': {   '30m': {   'body_ratio_threshold': 0.5,
                                                  'price_move_pct': 0.5,
                                                  'trail_stop_pct': 1.0,
                                                  'vol_len': 5,
                                                  'vol_multiplier': 3.0}},
                              'AEHR': {   '30m': {   'body_ratio_threshold': 0.5,
                                                     'price_move_pct': 4.0,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 1.5}},
                              'AFRM': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 0.5,
                                                     'trail_stop_pct': 1.5,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 2.5}},
                              'ALAB': {   '30m': {   'body_ratio_threshold': 0.5,
                                                     'price_move_pct': 1.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 2.5}},
                              'ALK': {   '30m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 0.5,
                                                    'trail_stop_pct': 2.5,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 2.5}},
                              'AMAT': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 0.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 2.0}},
                              'AMD': {   '30m': {   'body_ratio_threshold': 0.3,
                                                    'price_move_pct': 0.5,
                                                    'trail_stop_pct': 3.0,
                                                    'vol_len': 5,
                                                    'vol_multiplier': 1.2}},
                              'AMKR': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 2.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 2.5}},
                              'AOSL': {   '30m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 2.0,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 7,
                                                     'vol_multiplier': 1.5}},
                              'APO': {   '30m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 0.5,
                                                    'trail_stop_pct': 1.0,
                                                    'vol_len': 7,
                                                    'vol_multiplier': 3.0}},
                              'APTV': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 2.0,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 7,
                                                     'vol_multiplier': 2.0}},
                              'ARM': {   '30m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 3.5,
                                                    'trail_stop_pct': 1.0,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 1.5}},
                              'ARWR': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 3.5,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 1.5}},
                              'ASTS': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 0.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 2.5}},
                              'BE': {   '30m': {   'body_ratio_threshold': 0.7,
                                                   'price_move_pct': 3.5,
                                                   'trail_stop_pct': 2.0,
                                                   'vol_len': 5,
                                                   'vol_multiplier': 1.8}},
                              'BROS': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 2.5,
                                                     'trail_stop_pct': 1.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.0}},
                              'CEVA': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 0.5,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 7,
                                                     'vol_multiplier': 3.5}},
                              'CIEN': {   '30m': {   'body_ratio_threshold': 0.5,
                                                     'price_move_pct': 2.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 7,
                                                     'vol_multiplier': 1.2}},
                              'CRDO': {   '30m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 1.5,
                                                     'trail_stop_pct': 1.0,
                                                     'vol_len': 7,
                                                     'vol_multiplier': 1.8}},
                              'CSCO': {   '30m': {   'body_ratio_threshold': 0.5,
                                                     'price_move_pct': 2.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 1.2}},
                              'CVNA': {   '30m': {   'body_ratio_threshold': 0.5,
                                                     'price_move_pct': 3.5,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 0.5}},
                              'DAL': {   '30m': {   'body_ratio_threshold': 0.5,
                                                    'price_move_pct': 3.5,
                                                    'trail_stop_pct': 1.0,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 1.5}},
                              'DELL': {   '30m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.0,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 0.7}},
                              'DHI': {   '30m': {   'body_ratio_threshold': 0.3,
                                                    'price_move_pct': 4.0,
                                                    'trail_stop_pct': 1.0,
                                                    'vol_len': 7,
                                                    'vol_multiplier': 1.2}},
                              'ENTG': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 2.5,
                                                     'trail_stop_pct': 2.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 2.5}},
                              'GTLB': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 2.0,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 3.0}},
                              'HOOD': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 0.5,
                                                     'trail_stop_pct': 2.0,
                                                     'vol_len': 7,
                                                     'vol_multiplier': 2.5}},
                              'HPE': {   '30m': {   'body_ratio_threshold': 0.5,
                                                    'price_move_pct': 0.5,
                                                    'trail_stop_pct': 1.5,
                                                    'vol_len': 5,
                                                    'vol_multiplier': 2.0}},
                              'INTC': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 4.0,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 1.2}},
                              'IREN': {   '30m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 4.0,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 0.5}},
                              'ISRG': {   '30m': {   'body_ratio_threshold': 0.5,
                                                     'price_move_pct': 1.0,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 1.5}},
                              'IVZ': {   '30m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 3.0,
                                                    'trail_stop_pct': 2.5,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 1.2}},
                              'JOBY': {   '30m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 0.5,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 1.5}},
                              'KLAC': {   '30m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 0.7}},
                              'LEN': {   '30m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 0.5,
                                                    'trail_stop_pct': 1.0,
                                                    'vol_len': 5,
                                                    'vol_multiplier': 3.0}},
                              'LITE': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 0.5,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 2.0}},
                              'MPWR': {   '30m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 0.8,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 0.5}},
                              'MRNA': {   '30m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 0.8,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 2.0}},
                              'MRVL': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 3.0,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 1.8}},
                              'MWH': {   '30m': {   'body_ratio_threshold': 0.3,
                                                    'price_move_pct': 0.5,
                                                    'trail_stop_pct': 3.0,
                                                    'vol_len': 7,
                                                    'vol_multiplier': 3.0}},
                              'MXL': {   '30m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 1.5,
                                                    'trail_stop_pct': 2.5,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 3.5}},
                              'NBIS': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 3.5,
                                                     'trail_stop_pct': 1.5,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 2.0}},
                              'NXT': {   '30m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 3.0,
                                                    'trail_stop_pct': 2.0,
                                                    'vol_len': 5,
                                                    'vol_multiplier': 1.5}},
                              'QNT': {   '30m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 0.5,
                                                    'trail_stop_pct': 2.5,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 1.8}},
                              'RBLX': {   '30m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 0.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 1.2}},
                              'RCL': {   '30m': {   'body_ratio_threshold': 0.3,
                                                    'price_move_pct': 4.0,
                                                    'trail_stop_pct': 3.0,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 1.2}},
                              'REZI': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 3.0,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 1.2}},
                              'RIOT': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 3.5,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 2.0}},
                              'SIMO': {   '30m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 4.0,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 1.2}},
                              'STX': {   '30m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 4.0,
                                                    'trail_stop_pct': 3.0,
                                                    'vol_len': 10,
                                                    'vol_multiplier': 1.8}},
                              'TEAM': {   '30m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 1.5,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 1.8}},
                              'UAL': {   '30m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 0.5,
                                                    'trail_stop_pct': 3.0,
                                                    'vol_len': 7,
                                                    'vol_multiplier': 1.5}},
                              'VSAT': {   '30m': {   'body_ratio_threshold': 0.5,
                                                     'price_move_pct': 0.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 10,
                                                     'vol_multiplier': 1.8}},
                              'VSH': {   '30m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 4.0,
                                                    'trail_stop_pct': 3.0,
                                                    'vol_len': 7,
                                                    'vol_multiplier': 1.2}}}}
