PARAMS: dict = {   'MomentumV8Strategy': {   'ALAB': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 3.0,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 2.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.0}},
                              'ASTS': {   '10m': {   'body_ratio_threshold': 0.3,
                                                     'price_move_pct': 3.5,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 2.5,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.5}},
                              'ISRG': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 0.8,
                                                     'take_profit_pct': 1.5,
                                                     'trail_stop_pct': 3.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 2.0}},
                              'NXT': {   '10m': {   'body_ratio_threshold': 0.7,
                                                    'price_move_pct': 3.5,
                                                    'take_profit_pct': 2.0,
                                                    'trail_stop_pct': 3.0,
                                                    'vol_len': 7,
                                                    'vol_multiplier': 1.5}},
                              'VOYG': {   '10m': {   'body_ratio_threshold': 0.7,
                                                     'price_move_pct': 1.2,
                                                     'take_profit_pct': 2.0,
                                                     'trail_stop_pct': 1.0,
                                                     'vol_len': 5,
                                                     'vol_multiplier': 3.5}}}}
