PARAMS: dict = {   'MomentumV8Strategy': {   'ASTS': {   '10m': {   'body_ratio_threshold_long': 0.3,
                                                     'body_ratio_threshold_short': 0.5,
                                                     'price_move_pct_long': 2.5,
                                                     'price_move_pct_short': 3.5,
                                                     'take_profit_pct_long': 1.5,
                                                     'take_profit_pct_short': 1.5,
                                                     'trail_stop_pct_long': 1.5,
                                                     'trail_stop_pct_short': 3.5,
                                                     'vol_len': 10,
                                                     'vol_multiplier_long': 1.0,
                                                     'vol_multiplier_short': 3.5}},
                              'ISRG': {   '10m': {   'body_ratio_threshold_long': 0.3,
                                                     'body_ratio_threshold_short': 0.3,
                                                     'price_move_pct_long': 3.0,
                                                     'price_move_pct_short': 2.0,
                                                     'take_profit_pct_long': 1.5,
                                                     'take_profit_pct_short': 2.0,
                                                     'trail_stop_pct_long': 1.5,
                                                     'trail_stop_pct_short': 1.0,
                                                     'vol_len': 7,
                                                     'vol_multiplier_long': 3.5,
                                                     'vol_multiplier_short': 3.5}},
                              'VOYG': {   '10m': {   'body_ratio_threshold_long': 0.3,
                                                     'body_ratio_threshold_short': 0.7,
                                                     'price_move_pct_long': 3.0,
                                                     'price_move_pct_short': 1.0,
                                                     'take_profit_pct_long': 2.0,
                                                     'take_profit_pct_short': 2.0,
                                                     'trail_stop_pct_long': 1.0,
                                                     'trail_stop_pct_short': 3.5,
                                                     'vol_len': 7,
                                                     'vol_multiplier_long': 1.8,
                                                     'vol_multiplier_short': 3.5}}}}
